branch-defaults:
  master:
    environment: Google-on-Fire-App
environment-defaults:
  Google-on-Fire-App:
    branch: null
    repository: null
global:
  application_name: Google-on-Fire
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Puma with Ruby 2.6
    running on 64bit Amazon Linux/2.11.2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
