production_secret_key_base: 'zMX5ds65oRGlq3WF6c66v4b5IiPIpUSVrTkwpJ5dx4rPiodIQtN2BkqrDZgNxGQy0gbrGIntHdZv7nibJLJTbK6hxqCu3fSbm8U9hMeYM7MouUxhDjetIcKdgIf3IOjd5bnBBjlPAfNhX3MoPPkBYp92Q3Nj62nXRhkLCmJogRJ2TDmdupXJxgUqCy04tj5YXVwZHmhbW7RwL0wgPI6blt21CVbzPnb7iROC66CUzT4GdzUhryq2TN4A6FBClIzA'
test_secret_key_base: 'cbad8f4b265332e13bbbf819f1a21c44a1c81aff72f008ab98b9532542cb27a13f54c4a300473e141904db13a9dae53668a1a83d64d8bc996190faa053e48329'
development_secret_key_base: '287e1feae797c36863429159afe64d0beb563cbfd2f59d75b5bcfa54a9697223d7caee36d8af7142c9615bc534295544b588d6c36f1d8eeb7553514c54b7a142'

db_adapter: 'mysql2'
db_encoding: 'utf8'

db_default_username: 'root'
db_default_password: 'admin'
db_default_host: 'localhost'

db_dev_database: 'google_on_fire_development_new'

db_test_database: 'google_on_fire_test_new'

db_production_database: 'ebdb'
db_production_username: 'admin'
db_production_password: 'googleadmin'
db_production_host: 'aa1sx5z3gnf7ax.cqla6leq2yyq.us-west-2.rds.amazonaws.com'
db_production_port: '3306'