# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 287e1feae797c36863429159afe64d0beb563cbfd2f59d75b5bcfa54a9697223d7caee36d8af7142c9615bc534295544b588d6c36f1d8eeb7553514c54b7a142

test:
  secret_key_base: cbad8f4b265332e13bbbf819f1a21c44a1c81aff72f008ab98b9532542cb27a13f54c4a300473e141904db13a9dae53668a1a83d64d8bc996190faa053e48329

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: zMX5ds65oRGlq3WF6c66v4b5IiPIpUSVrTkwpJ5dx4rPiodIQtN2BkqrDZgNxGQy0gbrGIntHdZv7nibJLJTbK6hxqCu3fSbm8U9hMeYM7MouUxhDjetIcKdgIf3IOjd5bnBBjlPAfNhX3MoPPkBYp92Q3Nj62nXRhkLCmJogRJ2TDmdupXJxgUqCy04tj5YXVwZHmhbW7RwL0wgPI6blt21CVbzPnb7iROC66CUzT4GdzUhryq2TN4A6FBClIzA

